version: "2"

services:
  cuckoo:
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    command: daemon
    ports:
        - "2042:2042"
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /mnt/cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
    env_file:
      - ./vbox/config-file.env

  web:
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    ports:
      - "80:31337"
    depends_on:
      - mongo
      - elasticsearch
      - postgres
      - cuckoo
    command: web
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /mnt/cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
    env_file:
      - ./vbox/config-file.env

  api:
    depends_on:
      - postgres
      - cuckoo
    build:
      dockerfile: vbox/Dockerfile
      context: .
      args:
        - CUCKOO_UID=1000
    ports:
        - "8000:1337"
    command: api
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /mnt/cuckoo-storage/:/cuckoo/storage/
      - ./vbox/conf/:/cuckoo/conf/
    env_file:
      - ./vbox/config-file.env

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  elasticsearch:
    image: blacktop/elasticsearch:5.6
    volumes:
      - es-data:/usr/share/elasticsearch/data

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  mongo-data:
  es-data:
  postgres-data:
