version: "2"

services:
  # cuckoo:
  #   image: blacktop/cuckoo:2.0
  #   command: daemon
  #   networks:
  #     - cuckoo
  web:
    image: blacktop/cuckoo:2.0
    ports:
      - "80:31337"
    links:
      - mongo
      - elasticsearch
      - postgres
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MONGO_HOST=mongo
      - MONGO_TCP_PORT=27017
      - POSTGRES_HOST=postgres
      - POSTGRES_TCP_PORT=5432
    command: web
    networks:
      - cuckoo
  api:
    depends_on:
      - postgres
    image: blacktop/cuckoo:2.0
    ports:
      - "8000:1337"
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_TCP_PORT=5432
    command: api
    networks:
      - cuckoo
  # nginx:
  #   build: nginx/.
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "80:80"
  #   links:
  #     - mongo
  #   networks:
  #     - cuckoo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cuckoo
  elasticsearch:
    image: blacktop/elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - cuckoo
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA : /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - cuckoo

volumes:
  cuckoo-data:
  mongo-data:
  es-data:
  postgres-data:

networks:
  cuckoo:
    driver: bridge
